### ISSUE TITLE
Support grabbing screenshots of webpages

### ISSUE THREAD

**Issue by moshekaplan** [CylanceSPEAR/CyBot#3]
Support grabbing a screenshot of a webpage, as is done by sites like https://web-capture.net/.

**Comment by TonyLeeVT** [comment]
Thank you for the suggestion.  !screenshot will be in the next release coming soon!

**Comment by TonyLeeVT** [comment]
Thanks again for the suggestion.  We completed and provided the screenshot plugin.
[https://github.com/cylance/CyBot/tree/master/plugins/screenshot](https://github.com/cylance/CyBot/tree/master/plugins/screenshot)
