### ISSUE TITLE
Bug in CVE plugin regex validation

### ISSUE THREAD

**Issue by mikkos1** [CylanceSPEAR/CyBot#5]
CVE plugin is unable to provide information if CVE suffix is longer than four (4) numbers (e.g. 2019-11510).

**Comment by TonyLeeVT** [comment]
Thank you for the catch.  We updated the plugin to conform to the following format:  https://cve.mitre.org/cve/identifiers/syntaxchange.html#new

We also caught another bug in the process and added some error checking for CVE's that don't exist.  Please let us know if you spot anything else.

**Comment by mikkos1** [comment]
No problem, seems to be working now as intended.
